# Workflow para construir e testar um projeto .NET e criar uma imagem Docker.
name: .NET Build and Docker Push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar o .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restaurar dependências do projeto
      - name: Restore dependencies
        run: dotnet restore ./Eventos/Eventos.sln

      # Construir o projeto
      - name: Build project
        run: dotnet build ./Eventos/Eventos.sln --no-restore --configuration Release

      # Rodar testes
      - name: Run tests
        run: dotnet test ./Eventos/Eventos.sln --no-build --verbosity normal

      # Construir e enviar a imagem Docker
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          dockerfile: ./Eventos/Dockerfile
          context: ./Eventos
          tags: brenojosecoelho/ese_eventos:latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
